# Generated by Django 5.0.2 on 2024-06-22 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 22, 11, 19, 42, 755193, tzinfo=datetime.timezone.utc)),
        ),
    ]
