# Generated by Django 5.0.2 on 2024-06-22 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 22, 11, 20, 45, 905236, tzinfo=datetime.timezone.utc)),
        ),
    ]
